### ISSUE TITLE
Criar Roles com as permissões especificas.

### ISSUE THREAD

**Issue by gabubellon** [rougeth/pybr2021-discord-bot#1]
* Criar  as roles definindo especificamente quais as permissões que as mesmas podem ter
* Roles definidas aqui  https://discordpy.readthedocs.io/en/stable/api.html?highlight=discord%20permissions#discord.Permissions.view_guild_insight

Exemplo de possivel solução atribuindo apenas as pemissões sendo falsas
```python
    vol_permission = discord.Permissions.all()

    # Roles from here https://discordpy.readthedocs.io/en/stable/api.html?highlight=discord%20permissions#discord.Permissions.view_guild_insights
    # Manage roles
    manage_roles = [
        "manage_channels",
        "manage_emojis",
        "manage_guild",
        "manage_messages",
        "manage_nicknames",
        "manage_permissions",
        "manage_roles",
        "manage_webhooks",
    ]
    for role in manage_roles:
        setattr(vol_permission, role, False)
```

**Comment by gabubellon** [comment]
```toml
#Categoria Organização
[[categorie]]
name = "Organização"
position = 0
restict_access = true

# Canais da Organização
[[categorie.channel]]
name = "geral"
position = 0
voice = false

# Canais de texto
[[categorie.channel]]
name = "dev-null"
position = 1
voice = false

# Canais de Voz
[[categorie.channel]]
name = "Reuniões"
position = 2
voice = true

# Categoria Voluntário
[[categorie]]
name = "Voluntariado"
position = 0
restict_access = true

[[categorie.channel]]
name = "america-latine-es"
position = 0
voice = false

[[categorie.channel]]
name = "pt-es-enquete-encuestal"
position = 1
voice = false

[[roles]]
#TODO
```

Exemplo do `toml`a ser utlizado
